import { test, expect } from '@playwright/test'
import { readFileSync } from 'node:fs'
import type { FriezeFixture } from '../unit/friezeFixture.shared'

// The row count follows the DATA, not a literal — but Playwright cannot import
// `src/data/archive`, which reaches `embeds.csv?raw` through `embeds.ts` and is
// Vite-only. The frieze fixture is the sanctioned stand-in: one cell per
// archive item, regenerated by a unit test that fails on drift.
const ROWS = (
  JSON.parse(readFileSync('tests/e2e/fixtures/frieze-cells.json', 'utf8')) as FriezeFixture
).cells.length

test('no webgl2 falls back to a plain project list with no pin', async ({ page }) => {
  const errors: string[] = []
  page.on('console', (message) => {
    if (message.type() === 'error') errors.push(message.text())
  })
  page.on('pageerror', (error) => errors.push(String(error)))

  // Refuse only webgl2. WebGL1 is untouched, so the hero's shader keeps
  // working and this isolates the scene's own probe — launching Chromium with
  // WebGL disabled would kill the hero too.
  await page.addInitScript(() => {
    const original = HTMLCanvasElement.prototype.getContext
    HTMLCanvasElement.prototype.getContext = function (
      this: HTMLCanvasElement,
      contextId: string,
      ...args: unknown[]
    ) {
      if (contextId === 'webgl2') return null
      return (original as unknown as (id: string, ...rest: unknown[]) => unknown).call(
        this,
        contextId,
        ...args,
      )
    } as typeof HTMLCanvasElement.prototype.getContext
  })

  await page.goto('/')
  await page.waitForFunction(() => document.body.dataset.loaderState === 'done')
  await page.locator('#projects').waitFor()

  await expect(page.locator('#projects .scene-fallback .scene-fallback-link')).toHaveCount(4)
  await expect(page.locator('#projects .scene-scroll')).toHaveCount(0)
  await expect(page.locator('#projects canvas')).toHaveCount(0)

  // With no wall to draw, the stream stops being a twin and becomes the
  // archive: the whole thing, in normal flow.
  await expect(page.locator('#projects #archive.stream--visible')).toHaveCount(1)
  await expect(page.locator('#archive li.stream-item')).toHaveCount(ROWS)
  // No toolbar came back with it. The old Archive's filters, sorts and search
  // are gone for good, in this state as much as any other.
  await expect(
    page.locator('#archive input, #archive select, #archive [role="listbox"], #archive button'),
  ).toHaveCount(0)
  // The skip-past link is an affordance of the HIDDEN state, where 171 clipped
  // rows sit between the reader and the rest of the page. Here they are
  // ordinary content and there is nothing to skip.
  await expect(page.locator('#archive a.stream-skip')).toHaveCount(0)

  expect(errors).toEqual([])
})
