import { test, expect, type Page } from '@playwright/test'
import { readFileSync } from 'node:fs'
import { openScene, scrollToPlayhead, scrollToActTwo, readSvh, CANVAS } from './helpers/scene'
import { playheadForColumn, scrollTargetFor, volumeShotPlayhead } from '../../src/utils/sceneMotion'
import { columnsFromSvh } from '../../src/utils/navTarget'
import type { FriezeFixture } from '../unit/friezeFixture.shared'

/**
 * The stream — the archive's accessible twin — as the acceptance for pipeline 3.
 *
 * **Corrected 2026-09-10.** The plan has this spec consume `archive` and
 * `yearBlocks` from `src/data/archive`. It cannot: that module reaches
 * `embeds.csv?raw` through `embeds.ts`, a Vite-only import Playwright's loader
 * will not follow — the fixture's own docstring says so. Everything the plan
 * wanted from `archive` comes from `frieze-cells.json` instead (one cell per
 * item, regenerated by a unit test that fails on drift) and from the DOM:
 * `extent.blocks` IS `yearBlocks` (year and count, newest first), and
 * `cells.length` is `archive.length`. `playheadForItem(id, layout, extent)` is
 * `playheadForColumn(cell.col + cell.span / 2, extent)` by definition, so the
 * fixture cell stands in for the layout too.
 */

const fixture = JSON.parse(
  readFileSync('tests/e2e/fixtures/frieze-cells.json', 'utf8'),
) as FriezeFixture
const extent = fixture.extent
const ROWS = fixture.cells.length
const cellOf = (itemId: string) => fixture.cells.find((c) => c.itemId === itemId)!

/**
 * The row index that OPENS each year block, from the fixture's own counts.
 *
 * These are the rows whose focus is guaranteed to travel. Focus is gated on the
 * year block (assumption 27): a row inside the block already in frame is one
 * the reader can see, so it does not move the camera. Only a row that crosses a
 * boundary does — which makes a block's first row the one place the applied
 * position must equal that row's own cell target.
 */
const BLOCK_STARTS = extent.blocks.reduce<number[]>(
  (acc, b, i) => (i === 0 ? [0] : [...acc, acc[i - 1] + extent.blocks[i - 1].count]),
  [],
)

interface Metrics {
  columns: number
  wrapperTop: number
  wrapperHeight: number
  innerHeight: number
}

async function metrics(page: Page): Promise<Metrics> {
  const columns = columnsFromSvh(await readSvh(page))!
  expect(columns, 'data-svh must resolve to a whole column count').toBeGreaterThan(0)
  const box = await page.evaluate(() => {
    const w = document.querySelector('#projects .scene-scroll') as HTMLElement
    return {
      wrapperTop: w.getBoundingClientRect().top + window.scrollY,
      wrapperHeight: w.offsetHeight,
      innerHeight: window.innerHeight,
    }
  })
  return { columns, ...box }
}

/** Where the page must end up when `itemId` takes focus. */
function targetFor(itemId: string, m: Metrics): number {
  const cell = cellOf(itemId)
  const playhead = playheadForColumn(cell.col + cell.span / 2, extent)
  return scrollTargetFor(playhead, m.wrapperTop, m.wrapperHeight, m.innerHeight, m.columns)
}

/** The stream's rows in DOM order, which is the wall's reading order. */
const rowIds = (page: Page): Promise<string[]> =>
  page.$$eval('#archive li.stream-item', (els) =>
    els.map((el) => (el as HTMLElement).dataset.itemId!),
  )

const FOCUSABLE =
  'a[href], button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])'

/**
 * Focus the element immediately before the stream in DOCUMENT order, so the
 * next Tab enters it. Found rather than named: the stream is the first child of
 * `#projects`, and what precedes it is whatever the hero happens to end with.
 */
async function tabToStreamEdge(page: Page): Promise<void> {
  const ok = await page.evaluate((sel) => {
    const all = Array.from(document.querySelectorAll<HTMLElement>(sel)).filter(
      (el) => el.offsetParent !== null || getComputedStyle(el).position === 'fixed',
    )
    const first = all.findIndex((el) => el.closest('#archive'))
    if (first <= 0) return false
    all[first - 1].focus()
    return document.activeElement === all[first - 1]
  }, FOCUSABLE)
  expect(ok, 'could not find the focusable immediately before the stream').toBe(true)
}

/**
 * Reach a row with REAL Tab presses. `:focus-visible` is what turns a row into
 * the pill, and a scripted `.focus()` does not reliably match it, so a
 * `.focus()`-driven test can pass on a pill nobody can see.
 */
async function tabToRow(page: Page, index: number): Promise<string> {
  await tabToStreamEdge(page)
  // One Tab into the skip link, then one per row.
  for (let i = 0; i <= index + 1; i++) await page.keyboard.press('Tab')
  const id = await page.evaluate(
    () => (document.activeElement?.closest('li.stream-item') as HTMLElement | null)?.dataset.itemId ?? null,
  )
  expect(id, `Tab did not land on row ${index}`).toBe((await rowIds(page))[index])
  return id!
}

/** The focused element's pill geometry. */
const pillBox = (page: Page) =>
  page.evaluate(() => {
    const el = document.activeElement as HTMLElement
    const r = el.getBoundingClientRect()
    const cs = getComputedStyle(el)
    return { top: r.top, left: r.left, width: r.width, clipPath: cs.clipPath, position: cs.position }
  })

async function settledScrollY(page: Page, timeout = 4000): Promise<number> {
  return page.evaluate(
    (ms) =>
      new Promise<number>((resolve) => {
        let last = window.scrollY
        let still = 0
        const t0 = performance.now()
        const tick = (): void => {
          if (window.scrollY === last) still++
          else {
            still = 0
            last = window.scrollY
          }
          if (still >= 10 || performance.now() - t0 > ms) resolve(window.scrollY)
          else requestAnimationFrame(tick)
        }
        requestAnimationFrame(tick)
      }),
    timeout,
  )
}

test.describe('the stream', () => {
  test.describe.configure({ timeout: 120_000 })

  test('1 · loads, renders, and says nothing to the console', async ({ page }) => {
    const errors: string[] = []
    page.on('console', (m) => m.type() === 'error' && errors.push(m.text()))
    page.on('pageerror', (e) => errors.push(String(e)))

    await page.goto('/')
    await page.waitForFunction(() => document.body.dataset.loaderState === 'done')
    await page.locator('#projects .scene-canvas-wrap[data-ready="true"]').waitFor()
    expect(await page.locator('#root').innerHTML()).not.toBe('')

    await page.evaluate(() => window.scrollTo({ top: document.body.scrollHeight, behavior: 'instant' }))
    await page.waitForTimeout(1200)
    expect(errors).toEqual([])
  })

  test('2 · every piece is a row, and the year blocks account for all of them', async ({ page }) => {
    await openScene(page)
    await expect(page.locator('#archive li.stream-item')).toHaveCount(ROWS)

    const blocks = await page.$$eval('#archive .stream-year', (els) =>
      els.map((el) => ({
        year: Number((el as HTMLElement).dataset.year),
        label: el.querySelector('.stream-year-count')!.textContent!.trim(),
        rows: el.querySelectorAll('li.stream-item').length,
      })),
    )
    expect(blocks.map((b) => b.year)).toEqual(extent.blocks.map((b) => b.year))
    expect(blocks.map((b) => b.rows)).toEqual(extent.blocks.map((b) => b.count))
    for (const [i, b] of blocks.entries()) {
      expect(b.label, `the ${b.year} count must read its own number`).toContain(
        String(extent.blocks[i].count),
      )
    }
    expect(blocks.reduce((n, b) => n + b.rows, 0)).toBe(ROWS)

    const serials = await page.$$eval('#archive li.stream-item', (els) =>
      els.map((el) => Number((el as HTMLElement).dataset.serial)),
    )
    expect(serials[0]).toBe(ROWS)
    expect(serials.at(-1)).toBe(1)
    for (let i = 1; i < serials.length; i++) expect(serials[i - 1] - serials[i]).toBe(1)
  })

  test('3 · the origin word comes from the locale, not from the datum', async ({ page }) => {
    await openScene(page)

    const freelance = page.locator('#archive li[data-origin="freelance"]')
    expect(await freelance.count()).toBeGreaterThanOrEqual(1)
    await expect(freelance.first().locator('.workrow-meta')).toContainText('freelance')
    // `professional` is the default and says nothing worth a line.
    await expect(page.locator('#archive li[data-origin="professional"] .workrow-meta')).toHaveCount(0)

    await page.locator('.nav-lang').click()
    await page.waitForTimeout(600)
    // PT `freelance` is also `freelance`, so this half only proves the switch
    // did not erase the meta. The word that actually differs is `personal`.
    await expect(freelance.first().locator('.workrow-meta')).toContainText('freelance')

    const personal = page.locator('#archive li[data-origin="personal"]')
    const n = await personal.count()
    test.skip(n === 0, 'no personal piece yet (spec decision 9); re-armed by the first one that lands')
    await expect(personal.first().locator('.workrow-meta')).toContainText('pessoal')
  })

  test('4 · focusing a row travels the camera to its cell', async ({ page }) => {
    await openScene(page)
    await scrollToActTwo(page, 0)
    const m = await metrics(page)
    const ids = await rowIds(page)

    // A block's FIRST row is the one whose focus must land on its own cell:
    // every other row is gated by assumption 27. These three cover a WorkRow
    // (row 0 is a 2x2 case study at column 0), an editorial row in a middle
    // block, and the oldest block at the far end of the dolly.
    const cases = [BLOCK_STARTS[0], BLOCK_STARTS[2], BLOCK_STARTS[BLOCK_STARTS.length - 1]]
    // Which kind opens a block is the data's business, not this test's. Assert
    // the coverage that matters — both kinds are exercised somewhere — and let
    // the indices be whatever the years happen to start with.
    const kinds = new Set(cases.map((i) => cellOf(ids[i]).kind))
    const allStarts = new Set(BLOCK_STARTS.map((i) => cellOf(ids[i]).kind))
    expect(kinds.has('caseStudy')).toBe(true)
    if (allStarts.has('embed')) {
      const embedStart = BLOCK_STARTS.find((i) => cellOf(ids[i]).kind === 'embed')!
      if (!kinds.has('embed')) cases[1] = embedStart
    }

    for (const index of cases) {
      await scrollToActTwo(page, 0)
      const id = await tabToRow(page, index)
      const y = await settledScrollY(page)
      expect(Math.abs(y - targetFor(id, m)), `row ${index} (${id}) must park on its cell`).toBeLessThan(4)
      await expect(page.locator(CANVAS)).toHaveAttribute('data-act', '2')

      // The row is ABSOLUTE inside the fixed #archive container, so asserting
      // `position: fixed` on it would fail by design. The pill is the geometry.
      const pill = await pillBox(page)
      expect(pill.top).toBeCloseTo(16, 0)
      expect(pill.clipPath).toBe('none')
      expect(pill.position).toBe('absolute')
    }

    // The negative (assumption 27): the next row is inside the block now in
    // frame, so it is already visible and must not move the camera.
    const before = await settledScrollY(page)
    await page.keyboard.press('Tab')
    await page.waitForTimeout(1400)
    const sameBlock = await page.evaluate(
      () => !!document.activeElement?.closest('li.stream-item'),
    )
    expect(sameBlock, 'the next Tab must still be a row for this half to mean anything').toBe(true)
    expect(Math.abs((await settledScrollY(page)) - before)).toBeLessThan(4)
  })

  test('5 · the nav link lands on the volume shot', async ({ page }, testInfo) => {
    // `.nav-links` is `display: none` under 720 px and there is no mobile menu,
    // so the `#archive` link is a desktop affordance by design. Nothing to
    // click on `mobile-chromium`, and nothing broken either.
    test.skip(
      (testInfo.project.use.viewport?.width ?? 0) <= 720,
      'the nav centre links are hidden under 720px; there is no mobile menu',
    )
    await openScene(page)
    const m = await metrics(page)
    await page.locator('header .nav-link[href="#archive"]').click()
    const y = await settledScrollY(page)
    const want = scrollTargetFor(
      volumeShotPlayhead(m.columns),
      m.wrapperTop,
      m.wrapperHeight,
      m.innerHeight,
      m.columns,
    )
    expect(Math.abs(y - want)).toBeLessThan(2)
    await expect(page.locator(CANVAS)).toHaveAttribute('data-act', '2')
  })

  test('8 · the skip-past link is the first focusable, and it works', async ({ page }) => {
    await openScene(page)
    await scrollToActTwo(page, 0)

    await tabToStreamEdge(page)
    await page.keyboard.press('Tab')
    const first = await page.evaluate(() => ({
      cls: document.activeElement?.className,
      text: document.activeElement?.textContent,
      inStream: !!document.activeElement?.closest('#archive'),
    }))
    expect(first.inStream).toBe(true)
    expect(first.cls).toContain('stream-skip')
    expect(first.text).toMatch(/skip past all work|pular todos os trabalhos/i)

    const pill = await pillBox(page)
    expect(pill.top).toBeCloseTo(16, 0)
    expect(pill.clipPath).toBe('none')

    await page.keyboard.press('Enter')
    await page.waitForTimeout(1200)
    const landed = await page.evaluate(() => {
      const work = document.querySelector('#work')!.getBoundingClientRect()
      return { top: work.top, hash: location.hash, ih: window.innerHeight }
    })
    expect(landed.hash).toBe('#work')
    expect(Math.abs(landed.top)).toBeLessThan(landed.ih)
  })

  test('9 · traversal from both ends leaves nothing painted', async ({ page }) => {
    await openScene(page)
    await scrollToActTwo(page, 0)
    const ids = await rowIds(page)

    await tabToStreamEdge(page)
    await page.keyboard.press('Tab') // skip link
    const seen: string[] = []
    for (let i = 0; i < 5; i++) {
      await page.keyboard.press('Tab')
      const step = await page.evaluate(() => {
        const li = document.activeElement?.closest('li.stream-item') as HTMLElement | null
        return li
          ? { id: li.dataset.itemId!, serial: Number(li.dataset.serial), pilled: !!document.activeElement?.matches(':focus-visible') }
          : null
      })
      expect(step, `stop ${i} must be a row`).not.toBeNull()
      expect(step!.pilled, 'every stop is a pill').toBe(true)
      seen.push(step!.id)
    }
    expect(seen).toEqual(ids.slice(0, 5))

    // Back to the first row, then OUT. Only the last two presses count for the
    // "does not move" half: Shift+Tab through rows re-focuses them, and a
    // focused row is entitled to travel. Leaving is the part that must be inert.
    for (let i = 0; i < 4; i++) await page.keyboard.press('Shift+Tab')
    await page.waitForTimeout(1500)
    const before = await settledScrollY(page)

    await page.keyboard.press('Shift+Tab') // the skip link
    const atSkip = await settledScrollY(page)
    expect(
      Math.abs(atSkip - before),
      'the skip link is not a row and must not travel the camera',
    ).toBeLessThan(4)

    await page.keyboard.press('Shift+Tab') // out of the stream
    await page.waitForTimeout(900)
    expect(await page.locator('#archive :focus-visible').count()).toBe(0)
    // The page DOES move here, and should: focus landed on a real element far
    // up the document and the browser scrolled to it. What must not happen is a
    // camera travel — so the movement is the browser's, and the proof is that
    // the newly focused element is the thing now in view.
    const exited = await page.evaluate(() => {
      const el = document.activeElement as HTMLElement
      const r = el.getBoundingClientRect()
      return { inStream: !!el.closest('#archive'), top: r.top, bottom: r.bottom, ih: window.innerHeight }
    })
    expect(exited.inStream).toBe(false)
    expect(exited.bottom).toBeGreaterThan(0)
    expect(exited.top).toBeLessThan(exited.ih)

    // And out of the far end, forward into the rest of the page.
    await tabToRow(page, ids.length - 1)
    await page.keyboard.press('Tab')
    await page.waitForTimeout(400)
    expect(await page.evaluate(() => !!document.activeElement?.closest('#archive'))).toBe(false)
  })

  test('10 · rapid traversal re-aims one move rather than queueing many', async ({ page }) => {
    await openScene(page)
    await scrollToActTwo(page, 0)
    const m = await metrics(page)

    // End the burst on a row that OPENS a block, so the final focus is one the
    // gate cannot suppress and its target is the only correct answer. The burst
    // crosses two boundaries on the way (2026 → 2025 → 2024).
    const target = BLOCK_STARTS[2]
    expect(target, 'the burst must cross at least two year boundaries').toBeGreaterThan(40)
    const ids = await rowIds(page)

    await tabToStreamEdge(page)
    // No wait between presses: Lenis must replace the tween in flight, never
    // queue one per keystroke (assumption 28).
    for (let i = 0; i <= target + 1; i++) await page.keyboard.press('Tab')

    const focused = await page.evaluate(
      () => (document.activeElement?.closest('li.stream-item') as HTMLElement | null)?.dataset.itemId ?? null,
    )
    expect(focused).toBe(ids[target])

    const y = await settledScrollY(page, 8000)
    expect(
      Math.abs(y - targetFor(focused!, m)),
      'the LAST focus wins, not an earlier queued move',
    ).toBeLessThan(4)
  })

  test('11 · exiting from mid-stream does not reorder the document', async ({ page }) => {
    await openScene(page)
    await scrollToActTwo(page, 0)
    const ids = await rowIds(page)
    const deep = Math.floor(ids.length / 3)

    await tabToRow(page, deep)
    // Back to the skip link: one Shift+Tab per row plus one for the link.
    for (let i = 0; i <= deep; i++) await page.keyboard.press('Shift+Tab')
    expect(await page.evaluate(() => document.activeElement?.className)).toContain('stream-skip')

    await page.keyboard.press('Enter')
    await page.waitForTimeout(1200)
    expect(await page.evaluate(() => location.hash)).toBe('#work')

    // Shift+Tab from the first control after the stream returns to the LAST
    // row, not the first: the exit moved focus, not the document.
    await page.evaluate(() => (document.querySelector('#work button, #work a') as HTMLElement)?.focus())
    await page.keyboard.press('Shift+Tab')
    await page.waitForTimeout(400)
    const back = await page.evaluate(
      () => (document.activeElement?.closest('li.stream-item') as HTMLElement | null)?.dataset.itemId ?? null,
    )
    expect(back).toBe(ids.at(-1))
  })

  test('12 · the fixed container is why nothing else scrolls', async ({ page }) => {
    // Four scroll positions, a long Tab walk and a frame trace.
    test.setTimeout(240_000)
    await openScene(page)
    await scrollToPlayhead(page, 1)
    await page.waitForTimeout(600)

    // The premise the whole placement rests on: a 0x0 fixed container did not
    // prune the accessibility tree, and no ancestor re-parented the fixed box.
    await expect(
      page.getByRole('region', { name: /all work|todos os trabalhos/i }),
    ).toHaveCount(1)
    await expect(page.locator('#archive li.stream-item')).toHaveCount(ROWS)

    const centred = async (): Promise<{ dx: number; y: number }> =>
      page.evaluate(() => {
        const r = document.querySelector('#archive')!.getBoundingClientRect()
        // The LAYOUT viewport, not innerWidth: a classic scrollbar makes them
        // differ by its width, and `left: 50%` resolves against the former.
        return { dx: r.x - document.body.clientWidth / 2, y: r.y }
      })
    await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
    await page.waitForTimeout(300)
    let at = await centred()
    expect(Math.abs(at.dx)).toBeLessThan(1)
    expect(at.y).toBeCloseTo(16, 0)

    await scrollToPlayhead(page, 0.5)
    at = await centred()
    expect(Math.abs(at.dx)).toBeLessThan(1)
    expect(at.y).toBeCloseTo(16, 0)

    // Deep in act two, on the last row of a year block.
    await scrollToActTwo(page, 0.5)
    const m = await metrics(page)
    const ids = await rowIds(page)
    const boundary = await page.evaluate(() => {
      const items = Array.from(document.querySelectorAll('#archive li.stream-item'))
      for (let i = 0; i < items.length - 1; i++) {
        if (items[i].closest('.stream-year') !== items[i + 1].closest('.stream-year')) return i
      }
      return -1
    })
    expect(boundary).toBeGreaterThan(0)

    expect(boundary).toBe(BLOCK_STARTS[1] - 1)
    await tabToRow(page, boundary)
    await page.waitForTimeout(1600)

    // The NEXT row's clipped box is already on screen, so the browser's own
    // focus-scroll has nothing to do — shape A ruled out before a key is pressed.
    const nextBox = await page.evaluate((i) => {
      const items = Array.from(document.querySelectorAll('#archive li.stream-item'))
      const el = items[i + 1].querySelector('a') as HTMLElement
      const r = el.getBoundingClientRect()
      return { x: r.x, y: r.y, iw: window.innerWidth, ih: window.innerHeight }
    }, boundary)
    expect(nextBox.x).toBeGreaterThanOrEqual(0)
    expect(nextBox.x).toBeLessThanOrEqual(nextBox.iw)
    expect(nextBox.y).toBeGreaterThanOrEqual(0)
    expect(nextBox.y).toBeLessThanOrEqual(nextBox.ih)

    const projectsTop = await page.evaluate(
      () => document.querySelector('#projects')!.getBoundingClientRect().top + window.scrollY,
    )

    await page.keyboard.press('Tab')
    const trace = await page.evaluate(
      () =>
        new Promise<{ ys: number[]; sticky: number[] }>((resolve) => {
          const ys: number[] = []
          const sticky: number[] = []
          let still = 0
          const tick = (): void => {
            const s = document.querySelector('#projects .scene-sticky') as HTMLElement
            ys.push(window.scrollY)
            sticky.push((s?.scrollTop ?? 0) + (s?.scrollLeft ?? 0))
            const n = ys.length
            if (n > 1 && ys[n - 1] === ys[n - 2]) still++
            else still = 0
            if (still >= 10 || n > 400) resolve({ ys, sticky })
            else requestAnimationFrame(tick)
          }
          requestAnimationFrame(tick)
        }),
    )

    // Shape A: a native focus-scroll to the section's top.
    for (const y of trace.ys) expect(Math.abs(y - projectsTop)).toBeGreaterThan(4)
    // Shape B: the sticky box scrolled programmatically instead of the page.
    expect(Math.max(...trace.sticky)).toBe(0)
    // Monotonic: one eased move, not a jump out and back.
    const rising = trace.ys.at(-1)! >= trace.ys[0]
    for (let i = 1; i < trace.ys.length; i++) {
      if (rising) expect(trace.ys[i]).toBeGreaterThanOrEqual(trace.ys[i - 1] - 1)
      else expect(trace.ys[i]).toBeLessThanOrEqual(trace.ys[i - 1] + 1)
    }

    expect(Math.abs(trace.ys.at(-1)! - targetFor(ids[boundary + 1], m))).toBeLessThan(4)
    expect((await pillBox(page)).top).toBeCloseTo(16, 0)

    const z = await page.evaluate(() => ({
      stream: Number(getComputedStyle(document.querySelector('#archive')!).zIndex),
      nav: Number(getComputedStyle(document.querySelector('header.nav')!).zIndex),
    }))
    expect(z.stream).toBeGreaterThan(z.nav)

    // `pointer-events: none` is deliberate (the canvas keeps its hover), and
    // `elementFromPoint` skips such elements — so the plan's "elementFromPoint
    // returns the pill" is not satisfiable. Corrected 2026-09-10: assert the
    // invariant that IS true, and carry the stacking guarantee on z-index and
    // the containing-block check above.
    const hitThrough = await page.evaluate(() => {
      const el = document.activeElement as HTMLElement
      const r = el.getBoundingClientRect()
      const hit = document.elementFromPoint(r.left + r.width / 2, r.top + r.height / 2)
      return { isPill: hit === el || el.contains(hit), pe: getComputedStyle(el).pointerEvents }
    })
    expect(hitThrough.pe).toBe('none')
    expect(hitThrough.isPill, 'the pill must not take the pointer from the canvas').toBe(false)
  })
})

test.describe('the stream · reduced motion', () => {
  test.describe.configure({ timeout: 120_000 })
  test.use({ contextOptions: { reducedMotion: 'reduce' } })

  test('6 · the same rows, and every move applies in one step', async ({ page }, testInfo) => {
    const wide = (testInfo.project.use.viewport?.width ?? 0) > 720
    await page.goto('/')
    await page.waitForFunction(() => document.body.dataset.loaderState === 'done')
    await page.locator('#projects .scene-canvas-wrap[data-ready="true"]').waitFor()

    await expect(page.locator('#archive li.stream-item')).toHaveCount(ROWS)
    const firstFocusable = await page.evaluate(
      () => (document.querySelector('#archive a, #archive button') as HTMLElement).className,
    )
    expect(firstFocusable).toContain('stream-skip')

    const m = await metrics(page)
    // The nav link is desktop-only (`.nav-links` is hidden under 720 px), so
    // this half runs where the affordance exists. The row-focus half below runs
    // everywhere — that one is the reduced-motion claim that matters.
    if (wide) {
      await page.locator('header .nav-link[href="#archive"]').click()
      // No Lenis under reduced motion: the target applies at once.
      await page.waitForTimeout(100)
      const y = await page.evaluate(() => window.scrollY)
      const want = scrollTargetFor(
        volumeShotPlayhead(m.columns),
        m.wrapperTop,
        m.wrapperHeight,
        m.innerHeight,
        m.columns,
      )
      expect(Math.abs(y - want)).toBeLessThan(2)
    }

    // And a row in another year block applies immediately too.
    await scrollToActTwo(page, 0, { settle: 220 })
    const ids = await rowIds(page)
    const boundary = await page.evaluate(() => {
      const items = Array.from(document.querySelectorAll('#archive li.stream-item'))
      for (let i = 0; i < items.length - 1; i++) {
        if (items[i].closest('.stream-year') !== items[i + 1].closest('.stream-year')) return i + 1
      }
      return -1
    })
    await tabToRow(page, boundary)
    await page.waitForTimeout(100)
    const y2 = await page.evaluate(() => window.scrollY)
    expect(Math.abs(y2 - targetFor(ids[boundary], m))).toBeLessThan(4)
  })
})

test.describe('the stream · phone, no WebGL', () => {
  test.describe.configure({ timeout: 120_000 })

  test('7 · the visible archive fits every phone width', async ({ page }) => {
    await page.addInitScript(() => {
      const original = HTMLCanvasElement.prototype.getContext
      HTMLCanvasElement.prototype.getContext = function (
        this: HTMLCanvasElement,
        contextId: string,
        ...args: unknown[]
      ) {
        if (contextId === 'webgl2') return null
        return (original as unknown as (id: string, ...rest: unknown[]) => unknown).call(
          this,
          contextId,
          ...args,
        )
      } as typeof HTMLCanvasElement.prototype.getContext
    })

    for (const [width, height] of [
      [390, 844],
      [360, 800],
      [320, 568],
    ]) {
      await page.setViewportSize({ width, height })
      await page.goto('/')
      await page.waitForFunction(() => document.body.dataset.loaderState === 'done')
      await page.locator('#archive.stream--visible').waitFor()

      const shape = await page.evaluate(() => {
        const label = document.querySelector('.stream-year-label') as HTMLElement
        const item = document.querySelector('#archive li.stream-item') as HTMLElement
        const row = document.querySelector('#archive a.stream-row') as HTMLElement
        const title = row.querySelector('.stream-row-title') as HTMLElement
        const meta = row.querySelector('.stream-row-meta') as HTMLElement
        return {
          overflow: document.documentElement.scrollWidth - window.innerWidth,
          labelBottom: label.getBoundingClientRect().bottom,
          itemTop: item.getBoundingClientRect().top,
          labelPosition: getComputedStyle(label).position,
          titleBottom: title.getBoundingClientRect().bottom,
          metaTop: meta.getBoundingClientRect().top,
        }
      })
      expect(shape.overflow, `no horizontal overflow at ${width}px`).toBeLessThanOrEqual(1)
      expect(shape.labelBottom, `the year heading sits above its rows at ${width}px`).toBeLessThanOrEqual(
        shape.itemTop + 1,
      )
      expect(shape.labelPosition, `inline heading, not a sticky column, at ${width}px`).not.toBe('sticky')
      expect(shape.metaTop, `meta below the title at ${width}px`).toBeGreaterThanOrEqual(
        shape.titleBottom - 1,
      )
    }
  })
})
